###
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    //"id_user": null,
    "first_name": "FulanAAA",
    "last_name": "de Tal",
    "email": "fulano@tal.com",
    "phone_ddd": "123",
    "phone_number": "999999989",
    "address": "Rua Teste do teste",
    "city": "São Roque",
    "uf": "SP",
    "zip_code": "11325-655",
    "birth_date": "1931-03-21",
    "creation_date": "2021-08-17",
    "name_user":"teste",
    "passwd": "123456"
}
###

POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
    //"id_user": null,
    "product_name": "Tubo de esgoto 250mm * 1m",
    "qt_product": 10,
    "serial_number": 01008888,
    "creation_date": "2016-04-25",
    "sale_value": 200,
    "id_supplier": 1,
    "id_group": 2,
    "id_user": 1
}
###


POST http://localhost:3000/create-category HTTP/1.1
Content-Type: application/json

{
    "id": null,
    "name":"Educação",
    "user_id":9
}
###
POST http://localhost:3000/create-expense HTTP/1.1
Content-Type: application/json

{
    "id": null,
    "category_id":1,
    "user_id":6,
    "due_date":"2021-09-13",
    "release_date":"2021-06-25",
    "total":999.99
}

###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "fulano@teste.com",
    "password": "123"
}
###

GET http://localhost:3000/users

###

GET http://localhost:3000/products

###

GET http://localhost:3000/clients

###

GET http://localhost:3000/products_group

###

GET http://localhost:3000/selected_products

###

GET http://localhost:3000/suppliers

###

GET http://localhost:3000/budgets

###

GET http://localhost:3000/get-user/1

###

GET http://localhost:3000/get-expenses/user/1

###

GET http://localhost:3000/get-expenses/user/1/category/1

###

GET http://localhost:3000/get-expenses/user/1/expense/2

###


PUT http://localhost:3000/update-user HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "name":"Ermerson",
    "email":"fulano@teste.com",
    "phone": "99 99999 9999",
    "password":"123"
}
###


PUT http://localhost:3000/update-category HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "name":"Estética",
    "user_id":1
}

###
PUT http://localhost:3000/update-expense HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "category_id":1,
    "user_id":1,
    "due_date":"2021-09-13",
    "release_date":"2021-06-25",
    "total":2999.99
}

###
DELETE http://localhost:3000/delete-user/1

###

DELETE http://localhost:3000/delete-category/user/1/category/4

###


DELETE http://localhost:3000/delete-expense/user/1/expense/2

###